version: '3.4'

services:
  belbackend:
    container_name: belbe
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../app/src/:/app/
