version: '3.4'

services:
  belbackend:
    container_name: belbe
    environment:
      - DATABASE_URL=mysql+pymysql://bel:1234@beldb/local
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./app/:/code/app/
      - ./alembic/:/code/alembic
    networks:
      - belnet

  nginx:
    container_name: proxy
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/etc/nginx/ssl
    command: [ nginx-debug, '-g', 'daemon off;' ]
    networks:
      - belnet

  db:
    image: mariadb:10.10.2-jammy
    restart: always
    container_name: beldb
    environment:
      MYSQL_DATABASE: 'local'
      MYSQL_USER: 'bel'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/db:/var/lib/mysql:delegated
    networks:
      - belnet

networks:
  belnet:
    driver: bridge
